### ISSUE TITLE
[Mod1, Lab] Please use sudo for install podman

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#1]
In [[Mod1, Lab] - Lab introduction](https://github.com/jadebustos/ocp-science/blob/master/hands-on-lab-script/intro/README.md) > Clients > As prerequisite to use the containerized clients. Install podman and pull the container image in the workstation machine: `$ yum -y install podman`,

We need to instruct use **sudo** for install podman as example `sudo -i`.
<img width="1311" alt="Screenshot 2019-09-03 at 11 01 19 PM" src="https://user-images.githubusercontent.com/34668540/64195356-e7c34700-ce9e-11e9-9b9e-75aa73b7d487.png">

Can you please check once?

**Comment by jadebustos** [comment]
Fixed

**Comment by d-jana** [comment]
`podman pull` command also need sudo access:

sudo -i podman pull quay.io/rhte_2019/ocp-science-clients:latest

Can you please update that too?

**Comment by jadebustos** [comment]
Hi,

it is updated, but not pushed to the repository. I am finishing updating
the doc from the lab2.
____________________________________
Best wishes, José Ángel de Bustos Pérez

Formerly "Sith Project Leader"
My boss said that I intimidate my coworkes so I stared at him until he
apologized.
"Nunca discutas con un imbécil, te hará descender a su nivel y allí te
ganará por experiencia."
"Ciencia es aquello que entendemos lo suficientemente bien como para
explicarselo a un ordenador. Todo lo demás es arte." - Donald Knuth.

Twitter: @jadebustos
http://es.linkedin.com/in/jadebustos

jadebustos@gmail.com
