### ISSUE TITLE
[Mod3, Lab] Please add command to create my-file.txt file before upload.

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#10]
Please add command to create my-file.txt file before upload:
<img width="1321" alt="Screenshot 2019-09-05 at 8 00 10 PM" src="https://user-images.githubusercontent.com/34668540/64426252-b5e2f800-d0cb-11e9-92d5-6babfdcbd05a.png">

<img width="854" alt="Screenshot 2019-09-06 at 5 38 36 PM" src="https://user-images.githubusercontent.com/34668540/64426801-2c342a00-d0cd-11e9-95bd-40f0128b91b0.png">

One more suggestion, can we download my-file.txt to /tmp directory to avoid duplicate file error?
<img width="1323" alt="Screenshot 2019-09-05 at 8 09 53 PM" src="https://user-images.githubusercontent.com/34668540/64427382-c34db180-d0ce-11e9-9835-0496902c39df.png">
<img width="854" alt="Screenshot 2019-09-06 at 5 38 36 PM" src="https://user-images.githubusercontent.com/34668540/64427388-c5177500-d0ce-11e9-86db-76877a929b01.png">

**Comment by jadebustos** [comment]
There is no need to upload any my-file.txt. Those are just examples about how to use s3cmd.
