### ISSUE TITLE
[Mod3, Lab] Can we mention that cluster-apps domain should be there in any URL?

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#11]
Can we mention that cluster-apps domain should be there in any URL?
<img width="1320" alt="Screenshot 2019-09-05 at 8 03 54 PM" src="https://user-images.githubusercontent.com/34668540/64426941-8cc36700-d0cd-11e9-9966-11b2d68a9749.png">
<img width="1317" alt="Screenshot 2019-09-05 at 8 06 43 PM" src="https://user-images.githubusercontent.com/34668540/64426945-8df49400-d0cd-11e9-8b75-9e51ea4dc650.png">

**Comment by jadebustos** [comment]
fixed

**Comment by d-jana** [comment]
This seems become more complex but that okay if we provide value for S3_HOST, S3_PORT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET or instructions how to find obtain them to set.
<img width="1024" alt="Screenshot 2019-09-11 at 12 03 07 AM" src="https://user-images.githubusercontent.com/34668540/64640420-8dd6fa00-d427-11e9-97c9-9e1fdb37f88b.png">

Without these user will stuck again.

Can you please try to see by executing step by step?

Can we mention value for all these in descriptive "Hint" help?
