### ISSUE TITLE
[Mod3, Lab] Stuck with python error

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#12]
I am getting connection error in using python script:
<img width="1315" alt="Screenshot 2019-09-05 at 11 28 16 PM" src="https://user-images.githubusercontent.com/34668540/64427546-0e67c480-d0cf-11e9-9448-e8bbc8164f3d.png">

Can you please check once?

One more suggestion, can we instruct user to logout/exit from pod?

**Comment by jadebustos** [comment]
I have removed the scripts due to we will use s3cmd which is included in the clients container.
