### ISSUE TITLE
We need to mention S3_HOST and S3_PORT atleast

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#13]
This new implementation to redirect user seems to be little more confusing but that okay if we provide value for S3_HOST, S3_PORT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET or instructions how to find obtain them to set.
<img width="1024" alt="Screenshot 2019-09-11 at 12 03 07 AM" src="https://user-images.githubusercontent.com/34668540/64640420-8dd6fa00-d427-11e9-97c9-9e1fdb37f88b.png">

Without these user will stuck again.

Can you please try to see by executing step by step?

Can we mention value for all these in descriptive "Hint" help?

_Originally posted by @jadebustos in https://github.com/jadebustos/ocp-science/issues/11#issuecomment-529196574_

**Comment by jadebustos** [comment]
Hi, in the lab02 all of this is explained and we will detail it during the lab. However, I have added some more information to try to clarify it.
