### ISSUE TITLE
[Mod2, Lab1] No directory/folder namely resources/cluster-operator/

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#2]
In [[Mod2, Lab1] - Lab01: Deploy AMQ Streams](https://github.com/jadebustos/ocp-science/blob/master/hands-on-lab-script/amq-streams/README.md) > Deploying Kafka Cluster operator > Deploy operator and cluster operator and its related resources with: `oc apply -f resources/cluster-operator/ -n amq-streams`,
There was no directory/folder namely `resources/cluster-operator/` and no command is provided to clone a GitHub or other repository.
Console log:
[Mod1Lab.txt](https://github.com/jadebustos/ocp-science/files/3570679/Mod1Lab.txt)
<img width="763" alt="Screenshot 2019-09-03 at 11 00 19 PM" src="https://user-images.githubusercontent.com/34668540/64195245-9fa42480-ce9e-11e9-98b7-f7917a966bb0.png">

So user should stuck here like me. We need to provide something for this.

**Comment by jadebustos** [comment]
fixed
