### ISSUE TITLE
[Mod3, lab] Can we add instruction or command for ceph-nano pod running or not?

### ISSUE THREAD

**Issue by d-jana** [jadebustos/ocp-science#9]
Can we add instruction or command for ceph-nano pod running or not?
<img width="1321" alt="Screenshot 2019-09-05 at 7 32 20 PM" src="https://user-images.githubusercontent.com/34668540/64426214-a19efb00-d0cb-11e9-8cf4-6c0084010cb9.png">

**Comment by jadebustos** [comment]
fixed
